#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII  
bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc rule -a Chromium desktop='^1'
bspc rule -a firefox desktop='^1'
bspc rule -a Steam state=floating desktop='^9' 
bspc rule -a com.spotify.Client desktop='^10' 
bspc rule -a Alacritty desktop='^2' 
bspc rule -a Evince desktop='^4'  
bspc rule -a Org.gnome.Nautilus desktop='^3'  
bspc rule -a Code desktop='^5'  
bspc rule -a Eclipse desktop='^5'  

# Border
bspc config normal_border_color \#2E3436  # janela não ativa
bspc config active_border_color \#CCCCCC # ?
bspc config focused_border_color \#121617 # janela ativa
bspc config presel_feedback_color \#FFFFFF # ?

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
# picom -CGb &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

#Led
xset led 3 &
