#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#Monitor
/usr/local/bin/monitor.sh &

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^6' follow=on

# Border
bspc config normal_border_color \#2E3436  # janela não ativa
bspc config active_border_color \#CCCCCC # ?
bspc config focused_border_color \#121617 # janela ativa
bspc config presel_feedback_color \#FFFFFF # ?

# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

#Numlock
/usr/bin/numlockx &

#Picom
picom -b --config ~/.config/picom/picom.conf

#Nextcloud
com.nextcloud.desktopclient.nextcloud &

#Wallpaper
feh --bg-fill ~/Imagens/wallpapers/clairebell.jpg --bg-fill ~/Imagens/wallpapers/clairebell.jpg &
